config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      resources :followings, only: [:index]
      resources :followers, only: [:index]
    end
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets, expect: [:show, :index, :destroy]
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form_contain" %> <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |messages| %>
      <li><%= messages %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost, html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t(".compose") %>
  </div>
  <%= f.submit t(".post"), class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: t(".accept") %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind(<%= t ".change" %>, function() {
    var size_in_megabytes = this.files[0].size/Settings.size_in_megabytes/Settings.size_in_megabytes;
    if (size_in_megabytes > Settings.picture_size) {
      alert(<%= t ".msg_maximum" %>);
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= user_followings_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.size %>
    </strong>
    <%= t ".following" %>
  </a>
  <a href="<%= user_followers_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.size %>
    </strong>
    <%= t ".followers" %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.gravarta_size), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(".views_profile"), current_user %></span>
<span><%= pluralize current_user.microposts.count, t(".microposts") %></span>